### ISSUE TITLE
Fails to load files due to date parsing problems

### ISSUE THREAD

**Issue by dbratell** [andersle/gpxplotter#1]
I tried your script on some files I downloaded from Garmin but the scripts seem to have a date parsing problem:

```
Traceback (most recent call last):
 File "garmin-plotter.py", line 6, in <module>
   for track in read_gpx_file(file_name, maxpulse=187):
 File "C:\Users\Daniel\Anaconda3\lib\site-packages\gpxplotter\gpxread.py", line 283, in read_gpx_file
   'segments': [read_segment(i, maxpulse=maxpulse) for i in segments],
 File "C:\Users\Daniel\Anaconda3\lib\site-packages\gpxplotter\gpxread.py", line 283, in <listcomp>
   'segments': [read_segment(i, maxpulse=maxpulse) for i in segments],
 File "C:\Users\Daniel\Anaconda3\lib\site-packages\gpxplotter\gpxread.py", line 172, in read_segment
   data = get_point_data(point)
 File "C:\Users\Daniel\Anaconda3\lib\site-packages\gpxplotter\gpxread.py", line 142, in get_point_data
   time = extract_data(point, 'time', date_format)
 File "C:\Users\Daniel\Anaconda3\lib\site-packages\gpxplotter\gpxread.py", line 121, in extract_data
   return [formatter(child.data) for child in i.childNodes]
 File "C:\Users\Daniel\Anaconda3\lib\site-packages\gpxplotter\gpxread.py", line 121, in <listcomp>
   return [formatter(child.data) for child in i.childNodes]
 File "C:\Users\Daniel\Anaconda3\lib\site-packages\gpxplotter\gpxread.py", line 139, in date_format
   timeobj = datetime.strptime(string, '%Y-%m-%dT%H:%M:%S.%f%z')
 File "C:\Users\Daniel\Anaconda3\lib\_strptime.py", line 565, in _strptime_datetime
   tt, fraction = _strptime(data_string, format)
 File "C:\Users\Daniel\Anaconda3\lib\_strptime.py", line 362, in _strptime
   (data_string, format))
ValueError: time data '2019-10-02T11:11:44.000Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```

I suspect the problem is that it expects a lowercase z at the end, when the files have uppercase Z. I believe uppercase Z is also the most common (maybe only allowed) format for UTC.

**Comment by dbratell** [comment]
I verified that the problem is with the parsing of the trailing Z but neither %z, nor %Z works. Maybe because I'm running this in Windows and there is something wrong with the timezone database in Windows. *shrug* 

I'll do some ugly hack to get around it. Feel free to close if you don't know of a suitable fix.

**Comment by datachico** [comment]
I have the same issue.  I'm running this on a Mac, FYI.

**Comment by andersle** [comment]
I'm trying to figure out this error now. According to [wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations), "Z" part should give an offset from UTC and that is the motivation for using the`"%z` format string as this one is supposed to read this offset, see the format codes listed in the [Python docs](https://docs.python.org/3/library/datetime.html).

To try to get rid of this issue, I have updated the script to make use of the [dateutil](https://dateutil.readthedocs.io/en/stable/) package. Hopefully, this will solve the problem.

Could you try to see if this helped?

**Comment by geo7** [comment]
@andersle currently reading gpx files on mac os using gpx data from a garmin watch, if there's a particular code snippet that you'd like me to run let me know. `read_gpx_file` _seems_ to work for me, but I'm not too sure what I should be checking exactly.

**Comment by andersle** [comment]
@geo7: Thanks, then I think you have already tested enough. It seems that making use of [dateutil](https://dateutil.readthedocs.io/en/stable/) solved the problem others were having.
