### ISSUE TITLE
`read_gpx_file` may return NaN error

### ISSUE THREAD

**Issue by iamhyc** [andersle/gpxplotter#21]
The function `approximate_velocity` in `gpxread.py` may result into NaN error, when there is over one segment in one second.
The traceback information is provided below (some private information is omitted)
```
Traceback (most recent call last):
  File "./plotgpx.py", line 16, in <module>
    for track in read_gpx_file(the_file):
  File "~/anaconda3/envs/gps/lib/python3.7/site-packages/gpxplotter/gpxread.py", line 355, in read_gpx_file
    process_segment(segment, max_heart_rate=max_heart_rate)
  File "~/anaconda3/envs/gps/lib/python3.7/site-packages/gpxplotter/gpxread.py", line 306, in process_segment
    segment['velocity-level'] = cluster_velocities(segment['velocity'])
  File "~/anaconda3/envs/gps/lib/python3.7/site-packages/gpxplotter/common.py", line 190, in cluster_velocities
    labels = clu.fit_predict(vel)
  File "~/anaconda3/envs/gps/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1077, in fit_predict
    return self.fit(X, sample_weight=sample_weight).labels_
  File "~/anaconda3/envs/gps/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 982, in fit
    accept_large_sparse=False)
  File "~/anaconda3/envs/gps/lib/python3.7/site-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "~/anaconda3/envs/gps/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "~/anaconda3/envs/gps/lib/python3.7/site-packages/sklearn/utils/validation.py", line 721, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "~/anaconda3/envs/gps/lib/python3.7/site-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

The reason may exist in too many duplicate entries in `time : np.ndarray` when using `scipy.interpolate.UnivariateSpline`.
So I use the following workaround (insert after [gpxread.py#L250](https://github.com/andersle/gpxplotter/blob/f633b246014097261f13da8b98731f5d8ab3edca/gpxplotter/gpxread.py#L250)), and it works fine for my use case.
```python
if np.isnan(spline(time)).any():
      _rng = time.max() + 1
      _distance = [0] * (_rng)
      for i,val in enumerate(distance):
          _distance[ time[i] ] += val
      _time = np.array(range(_rng))
      _distance = np.array(_distance)
      spline = UnivariateSpline(_time, _distance, k=3)
```

I hope the maintainer could provide a more reliable fix asap, thanks!

**Comment by andersle** [comment]
(Note to self - this is related to #22 #20 and the usage of [UnivariateSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.html))

**Comment by andersle** [comment]
Would it be possible for you to share a gpx-file where this error occurs (with personal information removed)? I'm having trouble generating "fake" data to trigger the error. 

I will add a quick fix that just ignores the error to solve #20 and #22. (The motivation for this is that the velocities that are estimated here are probably of poor quality and I would prefer adding support for reading tcx files to get a proper velocity).

**Comment by iamhyc** [comment]
[gps-19-obs.gpx.txt](https://github.com/andersle/gpxplotter/files/6698551/gps-19-obs.gpx.txt)

Hi, I have uploaded the gpx file with simple obfuscation. The error message is the same.

**Comment by andersle** [comment]
Thanks a lot, you can delete that file now if you prefer. 

So it is doing an int on the elapsed time,

https://github.com/andersle/gpxplotter/blob/main/gpxplotter/gpxread.py#L306

Removing this line (``dtype=np.int_``) seems to fix the problem. I think I will add this (after checking that it does not change some other things like formatting etc. in some of the plotting routines).

**Comment by iamhyc** [comment]
Thanks for your efforts. It works for me.
