### ISSUE TITLE
Demo fails to run due to AttributeError

### ISSUE THREAD

**Issue by lmocsi** [andersle/gpxplotter#3]
The "Simple example for showing a track in a map, colored by heart rate" demo fails to run on my gpx file (exported from Garmin Connect), with the following error:
Traceback (most recent call last):
  File "b.py", line 10, in <module>
    save_map(fig, 'test-{}.html'.format(i))
  File "C:\Program Files\Python37\lib\site-packages\gpxplotter\mplplotting.py", line 420, in save_map
    mplleaflet.show(path=name, fig=fig, tiles=tile)
  File "C:\Program Files\Python37\lib\site-packages\mplleaflet\_display.py", line 180, in show
    save_html(fig, fileobj=f, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mplleaflet\_display.py", line 131, in save_html
    html = fig_to_html(fig, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mplleaflet\_display.py", line 84, in fig_to_html
    exporter.run(fig)
  File "C:\Program Files\Python37\lib\site-packages\mplleaflet\mplexporter\exporter.py", line 51, in run
    self.crawl_fig(fig)
  File "C:\Program Files\Python37\lib\site-packages\mplleaflet\mplexporter\exporter.py", line 118, in crawl_fig
    self.crawl_ax(ax)
  File "C:\Program Files\Python37\lib\site-packages\mplleaflet\mplexporter\exporter.py", line 123, in crawl_ax
    props=utils.get_axes_properties(ax)):
  File "C:\Program Files\Python37\lib\site-packages\mplleaflet\mplexporter\utils.py", line 267, in get_axes_properties
    'axes': [get_axis_properties(ax.xaxis),
  File "C:\Program Files\Python37\lib\site-packages\mplleaflet\mplexporter\utils.py", line 231, in get_axis_properties
    props['grid'] = get_grid_style(axis)
  File "C:\Program Files\Python37\lib\site-packages\mplleaflet\mplexporter\utils.py", line 241, in get_grid_style
    if axis._gridOnMajor and len(gridlines) > 0:
AttributeError: 'XAxis' object has no attribute '_gridOnMajor'

**Comment by andersle** [comment]
This one seems to be related to [this error in mplleaflet](https://github.com/jwass/mplleaflet/issues/75) for recent versions of matplotlib. I do not have a quick fix for this (other than downgrading matplotlib), but I will see if I can switch from mplleaftlet to something else.

**Comment by andersle** [comment]
(Swapping from mplleaflet to folium will be done in https://github.com/andersle/gpxplotter/pull/4)

**Comment by andersle** [comment]
Closed by #4
